export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";
export const GET_CART_LIST = "GET_CART_LIST";
export const CART_ADD_LOADING = "CART_ADD_LOADING";
export const UPDATE_CARTITEMS = "UPDATE_CARTITEMS"
